### ISSUE TITLE
Chi tiết các tính năng cần hoàn thành.

### ISSUE THREAD

**Issue by wu4ngg** [trduyTh4nh/SociaLife#6]
# Các tính năng cần hoàn thành bao gồm
- [x] Xem profile của người khác
- [x] Xóa thông báo
- [x] Fix nút Follow
- [x] Check email, mật khẩu
- [x] Like mềm
- [x] Sửa bài viết
- [ ] Share bài
- [ ] Tìm kiếm nhiều thứ hơn
- [ ] Bỏ SQLite, dùng Firebase
# Các tính năng đã hoàn thành bao gồm
- [x] Comment
- [x] Giờ mềm (Xem #8)
- [x] Đăng bài
- [x] Đăng nhập, đăng ký
- [x] Chỉnh sửa thông tin (Đã làm mềm, xem #8)
- [x] Hiện bài lên trang chủ
- [x] Hiện bài trên trang của chính mình
- [x] Theo dõi trên trang chủ
- [x] Đăng xuất
- [x] Xem mình đã theo dõi ai
- [x] Xóa bài viết (Đã fix chức năng csdl, xem #8)
